version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - MIX_ENV=dev
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - db
    command: sh -c "mix deps.get && mix deps.clean --all && mix deps.get && mix ecto.drop --force-drop && mix ecto.setup && mix phx.server && mix run priv/repo/seeds.exs"

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER= ${POSTGRES_USER}
      - POSTGRES_PASSWORD= ${POSTGRES_PASSWORD}
      - POSTGRES_DB= ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
