version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - MIX_ENV=dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=timemanager_dev
      - DATABASE_URL=ecto://postgres:postgres@db/timemanager_dev
    ports:
      - "4000:4000"
    depends_on:
      - db
    command: bash -c "mix deps.get && mix ecto.setup && mix phx.server"

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=timemanager_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
