name: Docker Compose Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose --version

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy using Docker Compose
        run: |
          # Utilise ssh pour se connecter à notre serveur distant
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} user@your-server-ip-address << 'ENDSSH'
            # Navigue vers le répertoire de l'application
            cd /path/to/your/app
            git pull
            docker-compose down
            docker-compose up -d
          ENDSSH

        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
